runai submit --name multiview-crl-cl-10\
 -i aicregistry:5000/nglazman:multiview-crl-vqvae-latest \
 --node-type A100 \
 --run-as-user \
 --gpu 1 \
 --cpu 16 \
 --cpu-limit 32 \
 --memory 64G --memory-limit 128G --project nglazman \
 -v /nfs:/nfs --large-shm --command -- python multiview-crl/main_multimodal.py \
                             --dataroot /nfs/home/nglazman \
                             --dataset_name ADNI_registered \
                             --encoder-type vqvae \
                             --vqvae-nb-levels 3 \
                             --vqvae-scaling-rates 2 2 2 \
                             --train-steps 50000 \
                             --vqvae-hidden-channels 48 \
                             --vqvae-embed-dim 24 \
                             --batch-size 2 \
                             --use-amp \
                             --workers 4 \
                             --scale-contrastive-loss 10 \
                             --model-id vqvae_upsample \
                             --gradient-accumulation-steps 4 \
                             --gradient-checkpointing \
                             --skip-recon-ratio 0.3 \
                             --image-spacing 1.0 \
                             --crop-margin  10
