_wandb:
    value:
        cli_version: 0.25.1
        e:
            3dn7jypc40f1uqlm1txgac3o9w62wud7:
                args:
                    - --batch_size=4
                    - --bt_lambda=0.001663005528974409
                    - --cache_dataset=True
                    - --cache_dir=/nfs/home/nglazman/cache/multiview
                    - --content_dim=128
                    - --content_ratios=[0.5, 0.5, 0.5]
                    - --content_size=48
                    - --content_style_levels=[0, 1, 2]
                    - --contrastive_level_weights=[1, 1, 1]
                    - --cross_view_negs_only=True
                    - --dataroot=/nfs/home/nglazman/data
                    - --dataset_name=ADNI_stripped
                    - --encoder_type=vqvae
                    - --gradient_accumulation_steps=4
                    - --gradient_checkpointing=True
                    - --image_spacing=1
                    - --labels_path=/nfs/home/nglazman/nmpevqvae/labels_cleaned_3class.csv
                    - --lr=0.0001390800163169354
                    - --mask_mode=fixed
                    - --moco_momentum=0.99
                    - --moco_queue_size=8192
                    - --pass_full_to_next_level=True
                    - --patch_contrastive=True
                    - --patch_grid=[4, 5, 4]
                    - --recon_loss_start_step=2000
                    - --resume_training=True
                    - --scale_contrastive_loss=2.891342782255579
                    - --scale_recon_loss=0.16261502627292532
                    - --separate_encoders=True
                    - --skip_recon_ratio=0.5
                    - --spatial_size=[150, 180, 150]
                    - --tau=0.421390544052914
                    - --total_dim=512
                    - --train_steps=70000
                    - --use_amp=True
                    - --vq_commitment_weight=0.25
                    - --vqvae_embed_dim=64
                    - --vqvae_hidden_channels=32
                    - --vqvae_nb_levels=3
                    - --vqvae_scaling_rates=[2, 2, 2]
                    - --workers=8
                codePath: scripts/sweep_train.py
                codePathLocal: scripts/sweep_train.py
                email: glazmann@yahoo.co.uk
                executable: /usr/bin/python
                host: sweep-8-0-0
                os: Linux-5.4.0-216-generic-x86_64-with-glibc2.35
                program: /nfs/home/nglazman/crl-2/multiview-crl/scripts/sweep_train.py
                python: CPython 3.12.13
                root: /nfs/home/nglazman/crl-2/multiview-crl
                startedAt: "2026-04-13T14:45:27.419693Z"
                writerId: 3dn7jypc40f1uqlm1txgac3o9w62wud7
        m: []
        python_version: 3.12.13
        t:
            "3":
                - 2
                - 14
            "4": 3.12.13
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 4
bt_lambda:
    value: 0.001663005528974409
cache_dataset:
    value: true
cache_dir:
    value: /nfs/home/nglazman/cache/multiview
content_dim:
    value: 128
content_ratios:
    value:
        - 0.5
        - 0.5
        - 0.5
content_size:
    value: 48
content_style_levels:
    value:
        - 0
        - 1
        - 2
contrastive_level_weights:
    value:
        - 1
        - 1
        - 1
cross_view_negs_only:
    value: true
dataroot:
    value: /nfs/home/nglazman/data
dataset_name:
    value: ADNI_stripped
encoder_type:
    value: vqvae
gradient_accumulation_steps:
    value: 4
gradient_checkpointing:
    value: true
image_spacing:
    value: 1
labels_path:
    value: /nfs/home/nglazman/nmpevqvae/labels_cleaned_3class.csv
lr:
    value: 0.0001390800163169354
mask_mode:
    value: fixed
moco_momentum:
    value: 0.99
moco_queue_size:
    value: 8192
pass_full_to_next_level:
    value: true
patch_contrastive:
    value: true
patch_grid:
    value:
        - 4
        - 5
        - 4
recon_loss_start_step:
    value: 2000
resume_training:
    value: true
scale_contrastive_loss:
    value: 2.891342782255579
scale_recon_loss:
    value: 0.16261502627292532
separate_encoders:
    value: true
skip_recon_ratio:
    value: 0.5
spatial_size:
    value:
        - 150
        - 180
        - 150
tau:
    value: 0.421390544052914
total_dim:
    value: 512
train_steps:
    value: 70000
use_amp:
    value: true
vq_commitment_weight:
    value: 0.25
vqvae_embed_dim:
    value: 64
vqvae_hidden_channels:
    value: 32
vqvae_nb_levels:
    value: 3
vqvae_scaling_rates:
    value:
        - 2
        - 2
        - 2
workers:
    value: 8
