wandb_version: 1

batch_size:
  value: 4
bt_lambda:
  value: 0.04212006420935269
cache_dataset:
  value: true
cache_dir:
  value: /nfs/home/nglazman/cache/multiview
content_dim:
  value: 128
content_ratios:
  value:
  - 0.5
  - 0.5
  - 0.5
content_size:
  value: 24
content_style_levels:
  value:
  - 0
  - 1
  - 2
contrastive_level_weights:
  value:
  - 1
  - 1
  - 1
cross_view_negs_only:
  value: true
dataroot:
  value: /nfs/home/nglazman/data
dataset_name:
  value: ADNI_stripped
encoder_type:
  value: vqvae
gradient_accumulation_steps:
  value: 4
gradient_checkpointing:
  value: true
image_spacing:
  value: 1
labels_path:
  value: /nfs/home/nglazman/nmpevqvae/labels_cleaned_3class.csv
lr:
  value: 0.0003901974230786033
mask_mode:
  value: learned
moco_momentum:
  value: 0.99
moco_queue_size:
  value: 8192
pass_full_to_next_level:
  value: true
patch_contrastive:
  value: true
patch_grid:
  value:
  - 4
  - 5
  - 4
recon_loss_start_step:
  value: 2000
resume_training:
  value: true
scale_contrastive_loss:
  value: 0.31002524503690787
scale_recon_loss:
  value: 0.14001226411785808
separate_encoders:
  value: true
skip_recon_ratio:
  value: 0.5
spatial_size:
  value:
  - 150
  - 180
  - 150
tau:
  value: 0.060338775054832865
total_dim:
  value: 512
train_steps:
  value: 70000
use_amp:
  value: true
vq_commitment_weight:
  value: 0.25
vqvae_embed_dim:
  value: 64
vqvae_hidden_channels:
  value: 96
vqvae_nb_levels:
  value: 3
vqvae_scaling_rates:
  value:
  - 2
  - 2
  - 2
workers:
  value: 8
