#!/usr/bin/env python3
"""Generate the frozen-probe and supervised-control SLURM arrays; never submit jobs."""

import argparse
import shlex
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.generate_encoder_ablation_slurm import load_resources  # noqa: E402


def render(kind, resources, steps, include_native):
    frozen = kind == "spatial_probes"
    names = ["conv_mlp_s42", "resnet_groupnorm_s42", "resnet_stride8_s42"] if frozen else ["t1", "flair"]
    directives = {
        "job-name": f"encoder-{kind.replace('_', '-')}-s42",
        "output": "/scratch/users/%u/%x-%A_%a.out",
        "error": "/scratch/users/%u/%x-%A_%a.err",
        "array": f"0-{len(names)-1}",
        "partition": resources["partition"],
        "gres": resources["gres"],
        "nodes": 1,
        "ntasks": 1,
        "mem": resources["mem"],
        "cpus-per-task": resources["cpus_per_task"],
        "time": resources["time"],
    }
    for key in ("constraint", "account", "qos"):
        if resources.get(key):
            directives[key] = resources[key]
    env = str(resources.get("conda_env", "multiview-env"))
    if not env or any(c not in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.-" for c in env):
        raise ValueError("Invalid conda environment name")
    module = str(resources.get("module", "anaconda3/2022.10-gcc-13.2.0"))
    if any("\n" in str(value) or "\r" in str(value) for value in [*directives.values(), module]):
        raise ValueError("Newlines are not supported in resources")
    command = (
        'COMMAND=("$PYTHON" -m eval.encoder_spatial_target_audit --run-dir "$RUNS/$NAME" '
        '--out-dir "$OUTPUT/spatial/${NAME}_${STAMP}" --device cuda --batch-size 4 --test-samples 400 '
        "--grids 1 2 --seed 1729" + (" --include-native" if include_native else "") + ")"
        if frozen
        else 'REFERENCE="${ENCODER_REFERENCE_RUN:-$RUNS/conv_mlp_s42}"\n'
        'COMMAND=("$PYTHON" -m training.encoder_target_control --run-dir "$REFERENCE" '
        '--out-dir "$OUTPUT/supervised/${NAME}_${STAMP}" --view "$NAME" --device cuda '
        f"--steps {steps} --batch-size 8 --width 24 --grid 8 --test-samples 400 --seed 42)"
    )
    return "\n".join(
        [
            "#!/bin/bash -l",
            "# Generated by scripts/generate_encoder_followups_slurm.py; no original run is overwritten.",
            *(f"#SBATCH --{key}={shlex.quote(str(value))}" for key, value in directives.items()),
            "",
            "set -euo pipefail",
            'REPO="${ENCODER_REPO:-${SLURM_SUBMIT_DIR:-$PWD}}"',
            f"CONDA_ENV_NAME={shlex.quote(env)}",
            'PYTHON="${ENCODER_PYTHON:-${HOME}/.conda/envs/${CONDA_ENV_NAME}/bin/python}"',
            'RUNS="${ENCODER_RUNS:-$REPO/results/encoder_ablations_slurm_bio/runs}"',
            'OUTPUT="${ENCODER_FOLLOWUPS:-/scratch/users/k24058220/encoder_followups_slurm_bio}"',
            'TASK_ID="${SLURM_ARRAY_TASK_ID:-${ENCODER_TASK_ID:-0}}"',
            f'if [[ ! "$TASK_ID" =~ ^[0-{len(names)-1}]$ ]]; then echo "Invalid task index: $TASK_ID" >&2; exit 2; fi',
            "NAMES=(" + shlex.join(names) + ")",
            'NAME="${NAMES[$TASK_ID]}"',
            'STAMP="${SLURM_ARRAY_JOB_ID:-${SLURM_JOB_ID:-preview}}_${TASK_ID}"',
            command,
            'if [[ "$#" -gt 1 ]]; then echo "Usage: $0 [--dry-run]" >&2; exit 2; fi',
            'case "${1:-}" in',
            "  --dry-run) printf '%q ' \"${COMMAND[@]}\"; printf '\\n'; exit 0 ;;",
            '  "") ;;',
            '  *) echo "Usage: $0 [--dry-run]" >&2; exit 2 ;;',
            "esac",
            'if [[ -z "${SLURM_JOB_ID:-}" ]]; then echo "Submit with sbatch; use --dry-run for preview." >&2; exit 2; fi',
            'cd "$REPO"',
            "test -f eval/encoder_spatial_target_audit.py && test -f training/encoder_target_control.py",
            f"module load {shlex.quote(module)}",
            'if [[ ! -x "$PYTHON" ]]; then echo "Python missing: $PYTHON" >&2; exit 1; fi',
            'export PYTHONPATH="$REPO" PYTHONNOUSERSITE=1 PYTHONUNBUFFERED=1 CUBLAS_WORKSPACE_CONFIG=:4096:8',
            "export OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1",
            'echo "Node: $(hostname) Job: $SLURM_JOB_ID Task: $TASK_ID ($NAME)"',
            '"$PYTHON" -c '
            + shlex.quote(
                "import torch; print(torch.__version__); assert torch.cuda.is_available(), 'No usable CUDA device'"
            ),
            'exec "${COMMAND[@]}"',
            "",
        ]
    )


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--cluster-config", type=Path, default=ROOT / "experiments/cluster/slurm_bio.yaml")
    p.add_argument("--output-dir", type=Path, default=ROOT / "experiments/generated")
    p.add_argument("--supervised-steps", type=int, default=2000)
    p.add_argument("--no-native", action="store_true", help="Probe only grids 1 and 2 to reduce disk/probe cost")
    args = p.parse_args(argv)
    if args.supervised_steps < 1:
        p.error("--supervised-steps must be positive")
    resources = load_resources(args.cluster_config)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    for kind in ("spatial_probes", "target_controls"):
        path = args.output_dir / f"encoder_{kind}_s42.slurm_bio.sh"
        path.write_text(render(kind, resources, args.supervised_steps, not args.no_native))
        path.chmod(0o755)
        print(path)
    print("Generated 3 frozen-probe tasks and 2 supervised-control tasks. No jobs submitted.")


if __name__ == "__main__":
    main()
